name: 'Pitest report'
description: 'Publish the pitest report'
inputs:
  name:
    description: Name of the check run
    required: false
    default: Pitest report
  file:
    description: Pitest report file (only supports xml)
    required: false
    default: '**/pit-reports/mutations.xml'
  summary:
    description: The results are published as part of the workflow summary
    required: false
    default: true
  annotation-types:
    description: Generate annotation for status (ALL, SURVIVED, KILLED)
    required: false
    default: SURVIVED
  output:
    description: Output location of the annotations (checks, summary)
    required: false
    default: checks
  max-annotations:
    description: Limit the number of annotations that are generated (max 50)
    required: false
    default: 10
  threshold:
    description: Fail if the test-strength is below the threshold
    required: false
    default: 0
  token:
    description: GitHub Access Token
    required: false
    default: ${{ github.token }}
outputs:
  killed:
    description: Total number of killed mutations
  survived:
    description: Total number of survived mutations
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'sliders'
  color: purple