on: [push]

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: Test the pitest report action
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Publish pitest report
        uses: ./
        with:
          file: 'mutations.xml'