on: [push]

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: Test pitest report action
    strategy:
      matrix:
        node-version: ["16"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Load cached node modules
        id: cached-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: modules${{ matrix.node-version }}-{{ $hashFiles('package-lock.json) }}
      - name: Install dependencies
        if: steps.cached-modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: Run all tests
        run: npm test